all:
	g++ -Ofast bitboards.cpp console.cpp data.cpp data.cpp evaluation.cpp hashKey.cpp init.cpp main.cpp makemove.cpp misc.cpp move.cpp movegen.cpp perft.cpp position.cpp pvTable.cpp search.cpp uci.cpp validate.cpp -o wuttang
